builds:
  - binary: whisper
    main: ./
    targets:
    - darwin_amd64
    - darwin_arm64
    - linux_386
    - linux_amd64
    - linux_arm
    - linux_arm64
    - windows_386
    - windows_amd64
    ldflags:
      - -X main.Version={{.Env.RELEASE_VERSION}}
      - -X main.CommitHash={{.Env.COMMIT_HASH}}
      - -X main.BuildTimestamp={{.Env.BUILD_TIMESTAMP}}

archives:
  - id: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: binary
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

changelog:
  skip: true

release:
  github:
    owner: SectorLabs
    name: whisper

  draft: false

  prerelease: auto

snapshot:
  name_template: "{{ incpatch .Version }}-next"
