name: Release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
      - "v*.*.*-pre.*"

permissions:
  contents: write

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.18'

    - name: Set release version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set the commit hash
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Set the build Timestamp
      run: echo "BUILD_TIMESTAMP=$(date +"%Y-%m-%dT%H:%M:%S")" >> $GITHUB_ENV

    - name: Release stable
      uses: goreleaser/goreleaser-action@v5
      if: (!contains(github.ref, '-pre.'))
      with:
        version: v1.22.1
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_HASH: ${{ env.COMMIT_HASH }}
        BUILD_TIMESTAMP: ${{ env.BUILD_TIMESTAMP }}

    - name: Generate CHANGELOG for pre-release
      if: contains(github.ref, '-pre.')
      id: changelog
      run: |
        echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        gh api repos/$GITHUB_REPOSITORY/releases/generate-notes \
          -f tag_name="${GITHUB_REF#refs/tags/}" \
          -f target_commitish=master \
          -q .body > tmp-CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release pre-release
      uses: goreleaser/goreleaser-action@v5
      if: contains(github.ref, '-pre.')
      with:
        version: v1.22.1
        args: release --clean --release-notes=tmp-CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GORELEASER_CURRENT_TAG: ${{ steps.changelog.outputs.RELEASE_TAG }}
        RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        COMMIT_HASH: ${{ env.COMMIT_HASH }}
        BUILD_TIMESTAMP: ${{ env.BUILD_TIMESTAMP }}
